codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 1%
        branches: null

    patch:
      default:
        target: auto
        threshold: 1%
        branches: null

    changes: false

  ignore: null

comment: false
