branches:
    only:
        - master

language: python
python:
    - 2.7
    - 3.5
    - 3.6

compiler:
    - g++

before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    - sudo apt-get -qq update
    - sudo apt-get install -y python-dev libfftw3-dev libeigen3-dev

    # List current contents of directories that should be being cached.
    - ls -la $HOME

    # Add ~/bin and ~/lib, etc. to the appropriate paths where scons install will put things.
    - export PYHOME=$HOME/virtualenv/python${TRAVIS_PYTHON_VERSION}
    - export PATH=$HOME/bin:$PYHOME/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
    - export MATPLOTLIBRC=$HOME/.matplotlib

    # Install GalSim
    - pip install -U setuptools pip
    - pip install -U numpy astropy future pyyaml LSSTDESC.Coord pybind11
    - pip install -U galsim

    # Install Pixmappy
    - git clone https://github.com/gbernstein/pixmappy.git
    - cd pixmappy; python setup.py install; cd ..

cache:
    pip: true
    directories:
    - $HOME/fitsio
    - $HOME/.matplotlib

install:
    - pip install -r requirements.txt
    - pip install nose codecov
    # Copy the .matplotlib directory to $HOME to force Agg backend.
    - cp -r tests/.matplotlib $HOME

script:
    - python setup.py install --prefix=$PYHOME
    - cd tests
    - nosetests --with-coverage --cover-package=piff --with-doctest

after_success:
    - coverage xml
    - codecov

before_cache:
    - rm -rf $HOME/.cache/pip/log
    - rm -rf $HOME/.cache/pip/http
