# This is just here in case we start needing to build platform-specific wheels.
# Currently Piff is pure python, so this is not required.

name: Build wheels and sdist and upload to PyPI

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y libffi-devel
          CIBW_BEFORE_ALL_MACOS: brew install libffi

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist and upload to PyPI
    needs: build_wheels
    # Just need to build sdist on a single machine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy setuptools
          pip install -U -r requirements.txt

      - name: Download wheels
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./wheels

      - name: Build sdist
        run: |
          python setup.py sdist
          ls -l dist
          tar tvfz dist/Piff-*.tar.gz

      - name: Copy wheels
        run: |
          echo ls -l wheels
          ls -l wheels
          echo ls -l wheels/artifact
          ls -l wheels/artifact
          cp wheels/artifact/*.whl dist
          echo ls -l dist
          ls -l dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: rmjarvis
            password: ${{ secrets.PYPI_PASSWORD }}
            verbose: true
