name: Build wheels and sdist and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build platform-independent wheel and sdist and upload to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/Piff/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip

          sudo -H apt-get -qq update
          sudo -H apt-get install -y libfftw3-dev libeigen3-dev

          pip install -U numpy setuptools wheel
          pip install -U -r requirements.txt

      - name: Build wheel
        run: |
          pip wheel -w wheels .
          ls -l wheels

      - name: Build sdist
        run: |
          python setup.py sdist
          cp wheels/Piff* dist
          ls -l dist
          tar tvfz dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            verbose: true
